### ISSUE TITLE
غیب شدن اینباند ها به طور ناگهانی

### ISSUE THREAD

**Issue by karimiorg** [MHSanaei/MHSanaei#1]
سلام از نسخه آخر پنل سنایی استفاده میکنم، اینباند هام پنهان شدند ولی کانفیگ ها متصل هستن و کار میکنند.

زمانی که این اتفاق افتاد نسخه پنل 1.6.1 بود و X-ray متوقف شد و من پنل رو آپدیت کردم ، اتصال برقرار شده ولی همچنان اینباند ها نیستند.

![image](https://github.com/MHSanaei/MHSanaei/assets/132637250/8866914f-f7de-4ef9-880a-285213cfb2be)

**Comment by MHSanaei** [comment]
به نظر میرسه بات برای پنل نصب کردید که باگ روی دیتابیس انداخته
بک اپ قدیمی رو بندازید
